declare class Scene_Map extends Scene_Base {
	private _waitCount: number;
	private _encounterEffectDuration: number;
	private _mapLoaded: boolean;
	private _touchCount: number;
	private _transfer: boolean;
	
	constructor();
	create(): void;
	isready(): boolean;
	onMapLoaded(): void;
	start(): void;
	update(): void;
	updateMainMultiply(): void;
	updateMain(): void;
	stop(): void;
	isBusy(): boolean;
	terminate(): void;
	needFadeIn(): boolean;
	needsSlowFadeOut(): boolean;
	updateWaitCount(): boolean;
	updateDestination(): void;
	isMapTouchOk(): boolean;
	processMapTouch(): void;
	isSceneChangeOk(): boolean;
	updateScene(): void;
	createDisplayObjects(): void;
	createSpriteset(): void;
	createAllWindows(): void;
	createMapNameWindow(): void;
	createMessageWindow(): void;
	createScrollTextWindow(): void;
	updateTransferPlayer(): void;
	updateEncounter(): void;
	updateCallMenu(): void;
	isMenuEnabled(): boolean;
	isMenuCalled(): boolean;
	callMenu(): void;
	updateCallDebug(): void;
	isDebugCalled(): boolean;
	fadeInForTransfer(): void;
	fadeOutForTransfer(): void;
	launchBattle(): void;
	stopAudioOnBattleStart(): void;
	startEncounterEffect(): void;
	updateEncounterEffect(): void;
	snapForBattleBackground(): void;
	startFlashForEncounter(): void;
	encounterEffectSpeed(): number;
}